### ISSUE TITLE
sidekiq:stop does not respect the configured shutdown timeout

### ISSUE THREAD

**Issue by codener** [makandra/makandra_sidekiq#2]
Sidekiq < 6 has two finishing timeouts: [one for finishing things itself](https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/manager.rb#L81) (A), and [one for `sidekiqctl` before killing a running Sidekiq instance](https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/ctl.rb#L77-L93) (B). The USAGE banner of `sidekiqctl` [advises to have B always greater than A](https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/ctl.rb#L26-L28), but if this is missed, you're in trouble: `sidekiqctl` kills the Sidekiq instance before it was able [to re-enqueue running jobs](https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/manager.rb#L128). As a result, **running jobs are lost!**.

Here's our invocation of `sidekiqctl`:
https://github.com/makandra/makandra_sidekiq/blob/c0f5958cbf2fdf6c645e7308a7ec8943be27b377/lib/makandra_sidekiq/sidekiq_control.rb#L97-L99

We should adapt it to read the configured Sidekiq timeout from `config/sidekiq.yml`, add 2 seconds and pass it to `sidekiqctl`. This way, B will be greater than A, and running jobs will be re-enqueued before exiting sidekiq.

**Comment by makmic** [comment]
Thank you for looking into this!
Please add a note to the Changelog, as people might be interested what caused a minor version jump :slightly_smiling_face:
