### ISSUE TITLE
Resolve deprecation warning for "Bundler.with_clean_env"

### ISSUE THREAD

**Issue by makmic** [makandra/makandra_sidekiq#6]
Recent versions of Bundler have deprectated the use of `Bundler.with_clean_env`, which is used by this gem (see [this file](https://github.com/makandra/makandra_sidekiq/blob/1fde092a37bfc8ccac1af78f8f2fe11b3641e580/lib/makandra_sidekiq/sidekiq_control.rb#L169))

The `sidekiq:start` prints this warning to the console:

> [DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env`

We should add some sort of version switch or duck typing to support both old and new bundler versions. [This issue in geordi](https://github.com/makandra/geordi/issues/77) might be related.

**Comment by codener** [comment]
The linked Geordi issue indeed about the same deprecation warning. makandra_sidekiq should move to `#with_original_env` in the same manner.

**Comment by dastra-mak** [comment]
The deprecation was introduced in bundler `2.1.0`. `2.0.2` is the latest version without deprecation.

**Comment by foobear** [comment]
Fixed in 0.2.1
