### ISSUE TITLE
Sidekiq 6 support

### ISSUE THREAD

**Issue by foobear** [makandra/makandra_sidekiq#7]
Sidekiq 6 has been out since August 2019. We should support it.

**Comment by KD6-3** [comment]
Sidekiq 6 doesn't [support](https://github.com/mperham/sidekiq/commit/5987a8c352a220a94e1850c79186d82c35050d85#diff-411201f0104d91346964914342a07cefL324) `--index` option anymore. To support Sidekiq 6 this needs to be fixed.

**Comment by denzelem** [comment]
Sidekiq 6 removed the `logfile`, `pidfile` and `daemonize` command line flags. We need to to rethink the init tooling, maybe with [god](https://github.com/mojombo/god) or the whole gem will be replaced with another solution.

**Comment by denzelem** [comment]
Some more information for this issue:

> Rails <5 is no longer supported. Rails 6+ only works in zeitwerk mode.

https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md

**Comment by triskweline** [comment]
I talked about this with @thomase @foobear and @ctriegg yesterday. We think this gem can probably be deprecated. [Procfiles](https://makandracards.com/opscomplete/67829-procfile-support) are a better solution to start a process on deploy/reboot and keep it running.

**Comment by codener** [comment]
@triskweline you're suggesting to not port this gem for Sidekiq 6+. Would we keep it for Sidekiq 5 and below, or migrate those to Procfiles as well?

There already is a version constraint on Sidekiq <6, so there is nothing to do for the moment.

**Comment by triskweline** [comment]
> Would we keep it for Sidekiq 5 and below, or migrate those to Procfiles as well?

We have a lot of existing projects using this gem. I don't think anyone will care to migrate them unless they want to use Sidekiq 6. We can keep this gem for existing Sidekiq 5 users, but not add new features.
